FROM node:10-alpine as builder
WORKDIR /client 
COPY package*.json ./
RUN npm install --production
COPY . .
RUN npm run build

FROM danjellz/http-server
WORKDIR /client
COPY --from=builder /client/build /client
